### ISSUE TITLE
Installing any new package via yarn throws an error.

### ISSUE THREAD

**Issue by jasonmacdonald** [OasisDigital/scalable-enterprise-angular#27]
Inside admin folder I ran...

```
yarn add loaderjs --save
yarn add v0.27.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/@oasisdigital%2ffruit-basket: Not found".
```

This happens for any package you try to install. How did you get around this error for adding new packages?

**Comment by kylecordes** [comment]
Jason - the issue you are seeing is a reason why this repo is a work-in-progress. It is actually a problem not with anything here, but with the underlying Lerna tool:

https://github.com/lerna/lerna/issues/884

Also, see this doc, which carries a recent, dire warning:

https://github.com/lerna/lerna/blob/master/doc/hoist.md

... considering these things, until they are fixed I should probably switch back to lerna+NPM, away form lerna+yarn, and also stop using --hoist (even though it provides considerable benefit for many-package projects).

**Comment by jasonmacdonald** [comment]
I see. Thank you for the information, helps a lot! Thought I was missing something.

**Comment by kylecordes** [comment]
This was made irrelevant by the switch to Nx; there is only one note modules and only one CLI application (all of the top) so installing packages works completely normally now.
